version: '3'
services:
  nginx:
      container_name: nginx-undangan-nikah-api
      platform: linux/amd64
      image: nginx:alpine3.18
      command: [ "nginx", "-g", "daemon off;" ]
      depends_on:
          - app
      links:
          - app
      working_dir: /var/www/html
      volumes:
          - ./docker/nginx/asset/:/etc/nginx/conf.d/
          - ./docker/nginx/log:/var/log/nginx/:rw
          - ./:/var/www/html:rw
      ports:
          - "${DOCKER_NGINX_PORT:-8000}:80"
      logging:
          options:
              max-size: "1m"
              max-file: "3"
  app:
      container_name: app-undangan-nikah-api
      build: ./docker/php
      working_dir: /var/www/html
      volumes:
          - ./:/var/www/html:rw